<?php

namespace AppBundle\Repository;

/**
 * preregisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class preregisterRepository extends \Doctrine\ORM\EntityRepository
{
}
