<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository {

    public function search($params) {

        $qb = $this->createQueryBuilder('u');

        $qb->addSelect('l')
                ->leftJoin('u.localite', 'l')
                ->addSelect('c')
                ->innerJoin('u.categories', 'c');
        $qb     ->andWhere('u.username LIKE :nom')
                ->andWhere('u.typeUser LIKE :type')
                ->setParameter('type','prestataire')
                ->setParameter('nom', '%' . $params['recherche_nom'] . '%');
                


        $qb->andwhere('l.localite LIKE :localite')
                ->setParameter('localite', '%' . $params['recherche_localite'] . '%');

        $qb->andWhere('c.nomCategorie LIKE :categorie')
                ->setParameter('categorie', '%' . $params['recherche_categorie'] . '%');



        return $qb->getQuery()
                  ->getResult();
    }

}
